spring.application.name=api-automatizacion-materiales

# ==============================
# PUERTO
# ==============================
server.port=8098

# ==============================
# SSH CONFIGURATION
# ==============================
ssh.host=10.91.80.99
ssh.port=22
ssh.user=tefext
ssh.password=tefext
ssh.remote.path=/opt/tef_extract/Certificacion/MATERIALES_NUMEROS_2026.xlsx

# ==============================
# SFTP CONFIGURATION BASE
# ==============================
sftp.port=22
sftp.user=tefabp1
sftp.password=Unix11!
sftp.remote.path=var/tfp/projs/rm/ext/Resource
sftp.script.order=ksh -l -c '. /tefabp/tefabp1/.profile; cd /tefabp/tefabp1/abp_home/core/bin; ./RM1OrderSync_Sh'
sftp.script.request=ksh -l -c '. /tefabp/tefabp1/.profile; cd /tefabp/tefabp1/abp_home/core/bin; ./RM1Request_Sh'

# ==============================
# SFTP CONFIGURATION UAT1
# ==============================
uat1.sftp.host=172.28.248.47

# ==============================
# SFTP CONFIGURATION UAT2
# ==============================
uat2.sftp.host=172.28.248.48

# ==============================
# SFTP CONFIGURATION UAT3
# ==============================
uat3.sftp.host=172.28.248.49

# ==============================
# SFTP CONFIGURATION UAT4
# ==============================
uat4.sftp.host=172.28.248.50


